### ISSUE TITLE
Herschikking homepage

### ISSUE THREAD

**Issue by YolanCristoria** [anneliesvanminsel/de-VeSt---afwerking#1]
Visie niet op eerste plaats,
wel onmiddelijk: de opleidingen + aanbod hoger staan

**Comment by anneliesvanminsel** [comment]
Alles is hier in orde, mss aanbod boven de opleidingen plaatsen?

**Comment by NHorward** [comment]
Ik vind het wel mooi en kleurrijk zo :) anders hebben we meteen die groene blokken?

**Comment by anneliesvanminsel** [comment]
Ja, inderdaad.. Met die groene blokken zat ik ook vast..

Maar zoals het nu is, is het inderdaad goed
