### ISSUE TITLE
Aanpassingen op de pagina

### ISSUE THREAD

**Issue by anneliesvanminsel** [anneliesvanminsel/de-VeSt---afwerking#18]
- Schoolbrochure schrappen
- Bereikbaarheid: betere pdf als tijdelijke oplossing (school ging dit nakijken)

**Comment by NHorward** [comment]
Schoolbrochure geschrapt!
Bereikbaarheid pdf nog niet ontvangen -> Nieuwe issue "Ontbrekende info"
